---
- hosts: webservers
  remote_user: root
  tasks:

    - name: Install apps-ssms
      npm:
        name: apps-ssms-test
        global: no
        path: /opt/apps-ssms-test

    - name: "move nginx.conf file"
      command: "cp -T /opt/apps-ssms-test/node_modules/apps-ssms-test/nginx.conf /etc/nginx/sites-enabled/apps-ssms-test.conf"
    
    - name: "nginx reload"
      command: "nginx -s reload"

...